
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FIRE = 7;
  public static final int COLON = 6;
  public static final int DAB = 10;
  public static final int $ = 3;
  public static final int HASHTAG = 12;
  public static final int EOF = 0;
  public static final int WORDONTHASTREET = 9;
  public static final int LSMILEY = 4;
  public static final int error = 1;
  public static final int MIXTAPE = 2;
  public static final int PARTY = 11;
  public static final int RSMILEY = 5;
  public static final int BONES = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MIXTAPE",
  "$",
  "LSMILEY",
  "RSMILEY",
  "COLON",
  "FIRE",
  "BONES",
  "WORDONTHASTREET",
  "DAB",
  "PARTY",
  "HASHTAG"
  };
}

