
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package com.madebyjeffrey;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PREACH = 19;
  public static final int PLAYA = 34;
  public static final int ONMYLEVEL = 22;
  public static final int TURNUP = 24;
  public static final int LPAREN = 27;
  public static final int REK = 16;
  public static final int DAB = 7;
  public static final int STAR = 40;
  public static final int YOSEWF = 17;
  public static final int RPAREN = 28;
  public static final int AKA = 4;
  public static final int WORDONTHASTREET = 6;
  public static final int BALLOUT = 13;
  public static final int DIGIT = 32;
  public static final int EOF = 0;
  public static final int LIT = 9;
  public static final int THROWMONEY = 12;
  public static final int error = 1;
  public static final int DOLLA = 26;
  public static final int NEWLINE = 37;
  public static final int CHECK = 15;
  public static final int OTHERLEVEL = 23;
  public static final int NOTLIT = 10;
  public static final int CUT = 14;
  public static final int COLON = 31;
  public static final int BOUNCE = 18;
  public static final int NETHING = 36;
  public static final int WEAK = 20;
  public static final int LETTER = 33;
  public static final int QM = 29;
  public static final int SON = 35;
  public static final int FIRE = 3;
  public static final int PUNC = 42;
  public static final int STREETNAME = 38;
  public static final int HASHTAG = 30;
  public static final int MIXTAPE = 2;
  public static final int WINNING = 21;
  public static final int AT = 41;
  public static final int BONES = 5;
  public static final int PARTY = 8;
  public static final int GETMONEY = 11;
  public static final int IDENTIFIER = 39;
  public static final int DEAD = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MIXTAPE",
  "FIRE",
  "AKA",
  "BONES",
  "WORDONTHASTREET",
  "DAB",
  "PARTY",
  "LIT",
  "NOTLIT",
  "GETMONEY",
  "THROWMONEY",
  "BALLOUT",
  "CUT",
  "CHECK",
  "REK",
  "YOSEWF",
  "BOUNCE",
  "PREACH",
  "WEAK",
  "WINNING",
  "ONMYLEVEL",
  "OTHERLEVEL",
  "TURNUP",
  "DEAD",
  "DOLLA",
  "LPAREN",
  "RPAREN",
  "QM",
  "HASHTAG",
  "COLON",
  "DIGIT",
  "LETTER",
  "PLAYA",
  "SON",
  "NETHING",
  "NEWLINE",
  "STREETNAME",
  "IDENTIFIER",
  "STAR",
  "AT",
  "PUNC"
  };
}

